spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# ... existing code ...

app:
  cors:
    # dev uchun: frontend portlaringiz
    allowed-origins: "http://localhost:3000,http://localhost:5173"
server:
  port: ${PORT:8080}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html   # foydalanuvchi shu bilan kiradi, u /swagger-ui/index.html ga redirect bo‘ladi
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
    disable-swagger-default-url: true